---
all:
  hosts:
    ## .........................................................................
    ## CLIENT:: setup
    client:
      ## ANSIBLE DEFAULTS
      ## _______________________
      ## NOTE: you need update public-key file for key selection in "playbooks/vars/default.yml"
      ## NOTE: by "{{ ansible_user }}-{{ ansible_host }}":
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519...
      # pl_a_cis_setup_ssh_pub_key: < cat ~/.ssh/id_ed25519...
      pl_a_cis_setup_ssh_pub_key: "..."
      ansible_user: <USERNAME>
      ansible_host: <192.168.0.0>
      ansible_port: 22
      ansible_host_hostname: "WFd8ScWIylnJVXzyvKP8k7aX"
      pl_a_service_name: "client_{{ ansible_user }}"
      install_server_git_user: "{{ ansible_user }}"
      # NOTE: change this to your email instead of user
      install_server_git_email: "{{ ansible_user }}"
      # NOTE: change to you needed dns and ntp server, or change in playbooks
      pl_a_host_default_dns: 9.9.9.9
      pl_a_host_default_ntp: time.cloudflare.com
      pl_a_host_fallback_ntp: ntp.ubuntu.com
      pl_a_time_synchronization_service: chrony # chrony | systemd-timesyncd
      ## ANSIBLE CLIENT ACCESS SETUP
      ## _______________________
      pl_a_user_setup: true
      pl_a_user_config: # ./pre-tasks.yml
        is_update: true
        ## sudo apt install whois && mkpasswd --method=sha-512
        password: "$6$BAyo.9vQm6NkOg0N$G8Gs39xyeqwRbsaG3HqPzaFJxAq3SQn9vYupTd0K2IinpHKi7YIn8ZI.RrKUjhS7WHf5vTr9y1a5hQKCxJ1hh1"
        group: sudo,adm,disk,dip,lxd,dialout,tty,lpadmin,plugdev,audio,video,render,input,bluetooth,netdev
        system: false
        append: true
        add_ssh_key: true
      ## CLIENT USED FOR ADDING TO SERVICES
      ## _______________________
      pl_a_clients:
        - name: "{{ ansible_user }}"
          dev: true # will used for install additional services per user as (git|zsh|tmux|nvim|python|go|npm)
          setup: false # if client should be setup with additional tools and gui (default true)
          updateOrCreate: false
        # rename to any user, to use without sudo
        - name: local_user
          dev: false # will used for install additional services per user as (git|zsh|tmux|nvim|python|go|npm)
          setup: true # if client should be setup with additional tools and gui (default true)
          shell: /bin/bash
          group: lpadmin,plugdev,audio,video,render,input,bluetooth,netdev
          createhome: true
          # sudo apt install whois && mkpasswd --method=sha-512
          password: "$6$YF.tKVjwypoJm.Mv$78Z7b5L40voqI7yftgm0atwXsYadn0hSaGvv7smtl4pXrOXhO7hqqchlT.UpaWhz0.JN/8wqC.TMtE4W9JTaN."
          # password: "!"
          updateOrCreate: true
          locale: de_DE.UTF-8
          language: de_DE.UTF-8
      ## UPDATER
      ## _______________________
      updater_time_timezone: Europe/Berlin
      updater_ntp_serivce_use_time_synchronization_service: "{{ pl_a_time_synchronization_service }}"
      updater_ntp_server: "{{ pl_a_host_default_ntp }}"
      updater_ntp_fallback_server: "{{ pl_a_host_fallback_ntp }}"
      ## NETPLAN
      ## _______________________
      pl_a_netplan_setup: false
      netplan_remove_existing: false
      # netplan_configuration:
      #   network:
      #     version: 2
      #     ethernets:
      #       "enp6s18":
      #         renderer: NetworkManager
      #         match: {}
      #         dhcp4: true
      #         networkmanager:
      #           # uuidgen
      #           uuid: "d18b4114-37b9-4b96-af69-6345636c5781"
      #           name: "netplan-enp6s18"
      #           passthrough:
      #             connection.timestamp: "1726957411"
      #             ipv6.method: "disabled"
      #             ipv6.ip6-privacy: "-1"
      #             proxy._: ""
      ## SSH
      ## NOTE: ssh not needed, is general setup by CIS
      ##       here only default conf to setup per user defaults
      ## _______________________
      pl_a_ssh_setup: true
      security_ssh_only_client_setup: true
      ## UFW
      ## _______________________
      ## NOTE: ufw is general setup by CIS
      ## NOTE: use here to set logging level and ssh if not setup by cis
      ## optional: use extend variable for add more ufw rules
      pl_a_ufw_setup_enable: true
      pl_a_ufw_logging_level: "medium" # low | medium | off
      # pl_a_ufw_rules_extended:
      #   - rule: allow
      #     to_port: 161
      #     protocol: udp
      #     interface: "{{ ansible_default_ipv4['interface'] }}"
      #     comment: "allow incoming connection on standard snmp port"
      ## SNMP
      ## _______________________
      pl_a_snmp_setup: false
      security_snmp_user: snmp
      security_snmp_password: <PASSWORD>
      security_snmp_encryption: <ENC>
      security_snmp_location: home
      security_snmp_contact: root
      security_snmp_address_ipv4: "{{ omit }}"
      security_snmp_address_ipv6: "{{ omit }}"
      security_snmp_port_ipv4: 161
      # security_snmp_port_ipv6: 161
      ## CIS
      ## _______________________
      pl_a_cis_setup: true
      pl_a_cis_setup_aide: false
      pl_a_cis_ipv6_required: true
      ## MAILING SETUP
      ## _______________________
      pl_a_mailing_mail_to: root # used in 'MAILTO' if cis-aide will used
      pl_a_mailing_mail_email: root@home.local
      pl_a_mailing_mail_username: "{{ pl_a_mailing_mail_email }}"
      pl_a_mailing_mail_password: ""
      pl_a_mailing_admin_mail_name: root
      pl_a_mailing_smtp_host: home.local
      pl_a_mailing_smtp_port: 465
      pl_a_mailing_remote_ssl: true
      pl_a_mailing_remote_starttls: false
      ## NULLMAILER SETUP
      ## _______________________
      pl_a_nullmailer_setup: false
      ## POSTFIX SETUP (most case not needed, by CIS nullmailer will set per default)
      ## _______________________
      pl_a_postfix_setup: false
      ## HARDENING SCAN
      ## _______________________
      pl_a_hardening_scan_setup: false
      pl_a_hardening_lynis_report_from: "{{ pl_a_mailing_mail_email }}"
      pl_a_hardening_lynis_report_to: "{{ pl_a_mailing_mail_email }}"
      ## HARDENING SECURITY
      ## _______________________
      pl_a_auditd_setup: true
      pl_a_fail2ban_setup: true
      security_fail2ban_proxmox: false
      ## DOCKER
      ## _______________________
      # pl_a_docker_user_shell: /bin/zsh
      cis_docker_is_swarm_mode: true
      cis_docker_rule_2_1: false # install docker as non root
      # cis_docker_install_release_fallback: plucky
      # cis_docker_install_release_skip: plucky
      # NOTE: add origins below if docker will install, without docker unattended will fail
      # pl_a_updater_unattended_allowed_origins_ext:
      #   - "Docker:${distro_codename}"
      # pl_a_updater_unattended_origins_patterns_ext:
      #   - "o=Docker,a=${distro_codename},l=Docker CE"
  ## ---------------------------------------------------------------------------
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    ## client playbook for install client (playbook-client-*.yml) + (playbook-s-cis.yml)
    clients:
      hosts:
        client:
    ## docker playbook (playbook-s-container.yml)
    docker:
      hosts:
        client:
