---
all:
  hosts:
    # CLIENT:: setup
    client:
      # NOTE: if some defaults needs to be skipped, en-commit next line
      # skip_default_setup:
      # ansible defaults
      #_______________________
      # NOTE: you need update public-key file for key selection in "playbooks/vars/default.yml"
      # NOTE: by "{{ ansible_user }}-{{ ansible_host }}"
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_user: username
      ansible_host: 192.168.250.0
      ansible_port: 22
      service_name: "server_{{ ansible_user }}"
      install_server_hostname: "WFd8ScWIylnJVXzyvKP8k7aX"
      install_server_git_user: "{{ ansible_user }}"
      install_server_git_email: "{{ ansible_user }}"
      # ansible client access setup
      #_______________________
      ansible_user_setup: yes
      ansible_user_config:
        is_update: yes
        # sudo apt install whois && mkpasswd --method=sha-512
        password: "$6$BAyo.9vQm6NkOg0N$G8Gs39xyeqwRbsaG3HqPzaFJxAq3SQn9vYupTd0K2IinpHKi7YIn8ZI.RrKUjhS7WHf5vTr9y1a5hQKCxJ1hh1"
        group: sudo,adm,cdrom,lpadmin,dip,plugdev,lxd,sambashare
        system: no
        append: yes
        add_ssh_key: yes
      # client used for adding to services
      #_______________________
      clients:
        # rename to any user, to use without sudo
        - name: local_user
          shell: /bin/bash
          group: adm,cdrom,lpadmin,dip,plugdev,lxd,sambashare
          createhome: yes
          # sudo apt install whois && mkpasswd --method=sha-512
          # password: "$6$Il3FROvn/RU9dfpy$kaTLw4ch.TQyY8KkBJdoZ1CkFiM19ypkJTG5I2sItsPGplwzknayHIHa0lllaSMqF4jpHbkb8vymTAks4yXuD."
          password: "!"
          updateOrCreate: yes
        - name: "{{ ansible_user }}"
          dev: yes
          updateOrCreate: no
      # netplan
      #_______________________
      netplan_setup: no
      netplan_remove_existing: no
      netplan_service_name: default
      netplan_configuration:
        network:
          ethernets:
            eth0:
              dhcp4: yes
              dhcp6: no
              addresses:
                - "{{ ansible_host }}/24"
              nameservers:
                addresses:
                  - 1.1.1.1
                  - 1.0.0.1
              gateway4: "{{ ansible_host.split('.')[0:3] | join('.') }}.1"
      # docker
      #_______________________
      docker_user_shell: /bin/zsh
      # ufw
      #_______________________
      ufw_setup: yes
      ufw_rules_extended:
        - rule: allow
          to_port: 22
          protocol: tcp
          interface: "{{ ansible_default_ipv4['interface'] }}"
          comment: "allow incoming connection on standard ssh port"
      # Ubuntu2004 CIS
      #_______________________
      cis_setup: yes
      # POSTFIX SETUP
      #_______________________
      postfix_setup: no
      postfix_mail_username: example@local
      postfix_mail_password: "mysecret"
      postfix_smtp_host: smtp.example.local
      # Hardening SCAN
      #_______________________
      hardening_scan: yes
      hardening_lynis_report_from: "{{ postfix_mail_username }}"
      hardening_lynis_report_to: "{{ postfix_mail_username }}"
    # SERVER:: setup
    server:
      # skip_default_setup:
      # ansible defaults
      #_______________________
      # NOTE: you need update public-key file for key selection in "playbooks/vars/default.yml"
      # NOTE: by "{{ ansible_user }}-{{ ansible_host }}"
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_user: username
      ansible_host: 192.168.250.0
      ansible_port: 22
      service_name: "server_{{ ansible_user }}"
      install_server_hostname: "WFd8ScWIylnJVXzyvKP8k7aX"
      install_server_git_user: "{{ ansible_user }}"
      install_server_git_email: "{{ ansible_user }}"
      # ansible client access setup
      #_______________________
      ansible_user_setup: yes
      ansible_user_config:
        is_update: yes
        # sudo apt install whois && mkpasswd --method=sha-512
        password: "$6$BAyo.9vQm6NkOg0N$G8Gs39xyeqwRbsaG3HqPzaFJxAq3SQn9vYupTd0K2IinpHKi7YIn8ZI.RrKUjhS7WHf5vTr9y1a5hQKCxJ1hh1"
        group: sudo,adm,cdrom,lpadmin,dip,plugdev,lxd,sambashare
        system: no
        append: yes
        add_ssh_key: yes
      # client used for adding to services
      #_______________________
      clients:
        - name: "{{ ansible_user }}"
          dev: yes
          updateOrCreate: no
      # netplan
      #_______________________
      netplan_setup: yes
      netplan_remove_existing: no
      netplan_service_name: default
      netplan_configuration:
        network:
          ethernets:
            eth0:
              dhcp4: yes
              dhcp6: no
              addresses:
                - "{{ ansible_host }}/24"
              nameservers:
                addresses:
                  - 1.1.1.1
                  - 1.0.0.1
              gateway4: "{{ ansible_host.split('.')[0:3] | join('.') }}.1"
      # docker
      #_______________________
      docker_user_shell: /bin/zsh
      # ufw
      #_______________________
      ufw_setup: yes
      ufw_rules_extended:
        - rule: allow
          to_port: 22
          protocol: tcp
          interface: "{{ ansible_default_ipv4['interface'] }}"
          comment: "allow incoming connection on standard ssh port"
      # Ubuntu2004 CIS
      #_______________________
      cis_setup: yes
      # POSTFIX SETUP
      #_______________________
      postfix_setup: yes
      postfix_mail_username: example@local
      postfix_mail_password: "mysecret"
      postfix_smtp_host: smtp.example.local
      # Hardening SCAN
      #_______________________
      hardening_scan: yes
      hardening_lynis_report_from: "{{ postfix_mail_username }}"
      hardening_lynis_report_to: "{{ postfix_mail_username }}"
  # ----------------------------------------------------------------------------
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    clients:
      hosts:
        client:
    servers:
      hosts:
        client:
        server:
    docker:
      hosts:
        client:
        server:
