---
# playbook server

# ------------------------------------------------------------------------------
- name: include pre-task playbook
  import_playbook: ./tasks/pre-tasks.yml
  remote_user: "{{ ansible_user }}"
  vars:
    ansible_user_conf_on_hosts:
      - servers
    ansible_user_conf_name: "{{ ansible_user }}"
    ansible_user_conf_update: "{{ ansible_user_config.is_update | bool }}"
    ansible_user_conf_shell: "{{ ansible_user_config.shell | default('/bin/bash') }}"
    ansible_user_conf_password: "{{ ansible_user_config.password }}"
    ansible_user_conf_group: "{{ ansible_user_config.group | default('adm,cdrom,sudo') }}"
    ansible_user_conf_system: "{{ ansible_user_config.system | default('no') | bool }}"
    ansible_user_conf_append: "{{ ansible_user_config.append | default('yes') | bool }}"
    ansible_user_conf_createhome: "{{ ansible_user_config.createhome | default('yes') | bool }}"
    ansible_user_conf_home: "{{ ansible_user_config.home | default('/home/' + ansible_user) }}"
    ansible_user_conf_add_ssh_key: "{{ ansible_user_config.add_ssh_key | default('yes') | bool }}"
  when: skip_default_setup is not defined and (ansible_user_setup is defined and ansible_user_setup | bool)
  # ----------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: cis installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - servers
  become: yes
  roles:
    ### -------------------------
    - role: ubuntu2004_cis
      ubuntu2004cis_rule_1_5_2: false # not work on ubuntu 21.03 pi
      ubuntu2004cis_rule_1_6_1: false # not work on ubuntu 21.03 pi
      ubuntu2004cis_rule_1_7_1_2: false # not work on ubuntu 21.03 pi
      ubuntu2004cis_rule_4_1_1_3: false # not work on ubuntu 21.03 pi
      when: cis_setup is defined and cis_setup | bool
    ### -------------------------

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: pre installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - servers
  vars:
    ufw_rules_default:
      - rule: allow
        to_port: 22
        protocol: tcp
        interface: "{{ ansible_default_ipv4['interface'] }}"
        comment: "allow incoming connection on standard ssh port"
  roles:
    ### -------------------------
    - role: ansible-updater
      when: skip_default_setup is not defined
    ### -------------------------
    - role: ansible-ssh
      when: skip_default_setup is not defined
    ### -------------------------
    - role: ansible-ufw
      become: yes
      ufw_rules: "{{ ufw_rules_default + ufw_rules_extended }}"
      when: skip_default_setup is not defined
    ### -------------------------
    - role: ansible-postfix
      become: yes
      postfix_hostname: "{{ postfix_mail_username.split('@')[1] }}.local"
      postfix_mailname: "{{ postfix_mail_username.split('@')[1] }}"
      postfix_aliases:
        - user: root
          alias: "{{ postfix_mail_username }}"
        - user: "{{ ansible_user }}"
          alias: "{{ postfix_mail_username }}"
      postfix_header_checks:
        - pattern: "/From:.*/"
          action: REPLACE
          text: "From: {{ postfix_mail_username }}"
      postfix_inet_interfaces: loopback-only
      postfix_relayhost: "{{ postfix_smtp_host }}"
      postfix_relaytls: true
      postfix_sasl_user: "{{ postfix_mail_username }}"
      postfix_sasl_password: "{{ postfix_mail_password }}"
      postfix_raw_options:
        - |
          sender_canonical_classes = envelope_sender
      when: skip_default_setup is not defined or (postfix_setup is defined and postfix_setup | bool)
    ### -------------------------

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: server installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - servers
  roles:
    ### -------------------------
    - role: ansible-install-server
      install_server_service_name: "{{ service_name }}"
      install_server_config:
        dev: yes
        apt_base: yes
        apt_dev: yes
        apt_exfat: yes
        apt_libs: yes # base|dev
        apt_vpn: yes
        apt_go: yes
        # snap_microk8s: no
        snap_btop: yes
        git: yes
        zsh: yes
        tmux: yes
        python: yes # base|dev
        # go: no
        # go_kompose: no
        npm: yes
        # mongodb: no
        java: yes # base|dev
    ### -------------------------
    - role: ansible-netplan
      netplan_service_name: "{{ service_name }}"
      when: netplan_setup is defined and netplan_setup | bool
    ### -------------------------

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: docker installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - docker
  roles:
    ### -------------------------
    - role: ansible-docker
      docker_user_shell: /bin/zsh
      docker_users_to_add_group: "{{ clients }}"
    ### -------------------------

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: run hardening scan
  remote_user: "{{ ansible_user }}"
  hosts:
    - servers
  become: yes
  roles:
    ### -------------------------
    - role: ansible-lynis
      lynis_deploy_method: git
      lynis_git_repo: "https://github.com/CISOfy/lynis"
      lynis_report_from: root@localhost
      lynis_report_to: root@localhost
      when: hardening_scan is defined and hardening_scan | bool
    ### -------------------------
