---
# playbook PRE

# ------------------------------------------------------------------------------
- name: PRE | configuration task (0) | include pre-task playbook
  import_playbook: ./pre-tasks.yml
  vars:
    ansible_user_conf_name: "{{ ansible_user }}"
    ansible_user_conf_update: "{{ pl_a_user_config.is_update | bool }}"
    ansible_user_conf_shell: "{{ pl_a_user_config.shell | default('/bin/bash') }}"
    ansible_user_conf_password: "{{ pl_a_user_config.password }}"
    ansible_user_conf_group: "{{ pl_a_user_config.group | default('adm,cdrom,sudo') }}"
    ansible_user_conf_system: "{{ pl_a_user_config.system | default('no') | bool }}"
    ansible_user_conf_append: "{{ pl_a_user_config.append | default('yes') | bool }}"
    ansible_user_conf_createhome: "{{ pl_a_user_config.createhome | default('yes') | bool }}"
    ansible_user_conf_home: "{{ pl_a_user_config.home | default('/home/' + ansible_user) }}"
    ansible_user_conf_add_ssh_key: "{{ pl_a_user_config.add_ssh_key | default('yes') | bool }}"
    ansible_user_conf_clients: "{{ pl_a_clients }}"
    ansible_host_conf_hostname: "{{ ansible_host_hostname | default(ansible_hostname) }}"
  when:
    - pl_a_user_setup is defined
    - pl_a_user_setup | bool

# ------------------------------------------------------------------------------
- name: HARDEN | configuration task (4) | include mailing playbook
  import_playbook: ./playbook-s-pre-mailing.yml
