---
# playbook server

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: HARDEN PLAYBOOKS
  ansible.builtin.import_playbook: playbook-sec-short.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Server installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - servers
  roles:
    ### -------------------------
    - role: ansible-install-server
      clients: "{{ pl_a_clients }}"
      install_server_service_name: "{{ pl_a_service_name }}"
      install_server_config:
        env_tun_setup: true
        # APT (1) -------------------------------
        apt_base: true
        apt_cert: true
        apt_qemu_guest_agent: true
        # OTHER --------------------------------
        inst_git_conf: true
        inst_zsh_conf: true

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Docker installer
  ansible.builtin.import_playbook: playbook-s-docker.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Kubernetes installer
  ansible.builtin.import_playbook: playbook-s-kubernetes.yml
