---
# playbook client

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: HARDEN PLAYBOOKS
  ansible.builtin.import_playbook: playbook-sec-short.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Server installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - clients
  roles:
    ### -------------------------
    - role: ansible-install-server
      clients: "{{ pl_a_clients }}"
      install_server_service_name: "{{ pl_a_service_name }}"
      install_server_config:
        dev: true
        env_tun_setup: true
        # APT -------------------------------
        apt_base: true
        apt_exa: false
        apt_eza: true
        apt_bat: true
        apt_auth_priv: true
        apt_cert: true
        apt_archive: true
        apt_dev: true
        apt_build: true
        apt_libs: true
        apt_snap: true
        apt_vpn_wireguard: true
        apt_qemu_guest_agent: true
        apt_latex: true
        apt_pandoc: true
        apt_apt_john_the_ripper: true
        apt_nmap: true
        # SNAP ----------------------------------
        snap_btop: true
        snap_glow: true
        # OTHER --------------------------------
        inst_git_conf: true
        inst_fonts: true
        inst_zsh_conf: true
        inst_tmux_conf: true
        inst_nvim_conf: true
        # PYTHON --------------------------------
        apt_python: true
        apt_python_pip: true
        apt_python_venv: true
        apt_python_dev: true
        pip_s_tui: true
        pip_autopep8: true
        pip_black: true
        pip_mypy: true
        pip_pre_commit: true

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Client installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - clients
  roles:
    ### -------------------------
    - role: ansible-install-client
      clients: "{{ pl_a_clients }}"
      install_client_service_name: "{{ pl_a_service_name }}"
      install_client_config:
        # GENERAL -------------------------------
        dev: true
        # GNOME ---------------------------------
        gnome_gui_setup: true
        gnome_gui_setup_extensions: true
        gnome_gui_setup_extensions_git_blur_shell: true
        gnome_gui_setup_extensions_git_dash_to_panel: true
        gnome_gui_setup_overlay: true
        gnome_terminal_setup_overlay: true
        # cleanup_remove_snap: false
        # cleanup_remove_flatpak: false
        # APT -----------------------------------
        apt_base: true
        apt_auth_priv: true
        apt_ubuntu: true
        apt_archive: true
        apt_snap: true
        apt_flatpak: true
        # DPKG ----------------------------------
        dpkg_veracrypt: true
        dpkg_brim: true
        # APPIMAGE ------------------------------
        app_image_logseq: true
        # SNAP ----------------------------------
        snap_chromium: true
        snap_firefox: true
        snap_onlyoffice: true
        snap_drawio: true
        snap_inkscape: true
        snap_android_studio: true
        snap_beekeeper_studio: true
        snap_dbeaver: true
        snap_code: true
        snap_insomnia: true
        snap_remmina: true
        snap_mqtt_explorer: true
        # FLATPAK -------------------------------
        flatpak_cryptomator: true
        flatpak_flatseal: true
        flatpak_haruna: true
        flatpak_upscayl: true
        flatpak_warp: true
        flatpak_ghidra: true
        flatpak_zaproxy: true
        # OTHER -------------------------------
        firefox_setup: true

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Container installer
  ansible.builtin.import_playbook: playbook-s-container.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: PenTest installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - clients
  roles:
    ### -------------------------
    - role: ansible-pentest
