---
# playbook server

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: cis installer
  ansible.builtin.import_playbook: playbook-s-cis.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: pre installer
  ansible.builtin.import_playbook: playbook-s-pre-install.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: server installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - servers
  roles:
    ### -------------------------
    - role: ansible-install-server
      install_server_service_name: "{{ service_name }}"
      install_server_config:
        dev: yes
        apt_base: yes
        apt_dev: yes
        apt_exfat: yes
        apt_libs: yes # base|dev
        apt_vpn: yes
        apt_go: yes
        # apt_rasp_pi_pkg: no
        # apt_qemu_guest_agent: no
        # dpkg_...: no
        # snap_...: no
        # snap_microk8s: no
        snap_btop: yes
        git: yes
        zsh: yes
        tmux: yes
        python: yes # base|dev
        # go: no
        # go_kompose: no
        ruby: yes
        npm: yes
        # mongodb: no
        java: yes # base|dev
    ### -------------------------
    - role: ansible-netplan
      netplan_service_name: "{{ service_name }}"
      when: netplan_setup is defined and netplan_setup | bool
    ### -------------------------

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: docker installer
  ansible.builtin.import_playbook: playbook-s-docker.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: kubernetes installer
  ansible.builtin.import_playbook: playbook-s-kubernetes.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: hardening scan
  ansible.builtin.import_playbook: playbook-s-hardening.yml
