---
# playbook server

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: CIS installer
  ansible.builtin.import_playbook: playbook-s-cis.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Pre installer
  ansible.builtin.import_playbook: playbook-s-pre-install.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Hardening scan
  ansible.builtin.import_playbook: playbook-s-hardening.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Server installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - servers
  roles:
    ### -------------------------
    - role: ansible-install-server
      clients: "{{ pl_a_clients }}"
      install_server_service_name: "{{ pl_a_service_name }}"
      install_server_config:
        dev: true
        env_tun_setup: true
        # APT (1) -------------------------------
        apt_base: true
        # apt_archive: false
        apt_dev: true
        apt_exfat: true
        apt_libs: true
        # APT (2) -------------------------------
        apt_vpn: true
        apt_go: true
        # apt_php: false
        # apt_rasp_pi_pkg: false
        # apt_qemu_guest_agent: false
        # DPKG ----------------------------------
        # dpkg_...: false
        # SNAP ----------------------------------
        # snap_microk8s: false
        # snap_multipass: false
        snap_btop: true
        # OTHER --------------------------------
        git: true
        zsh: true
        tmux: true
        python: true
        python_pip: true
        # python_pip_update: false
        python_venv: true
        python_dev: true
        # go_kompose: false
        ruby: true
        npm: true
        # mongodb: false
        java: true # base|dev
    ### -------------------------

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Docker installer
  ansible.builtin.import_playbook: playbook-s-docker.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Kubernetes installer
  ansible.builtin.import_playbook: playbook-s-kubernetes.yml
