---
# playbook server

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: CIS installer
  ansible.builtin.import_playbook: playbook-s-cis.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Pre installer
  ansible.builtin.import_playbook: playbook-s-pre-install.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Hardening scan
  ansible.builtin.import_playbook: playbook-s-hardening.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Server installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - servers
  roles:
    ### -------------------------
    - role: ansible-install-server
      install_server_service_name: "{{ service_name }}"
      install_server_config:
        dev: true
        env_tun_setup: true
        # APT (1) -------------------------------
        apt_base: true
        # apt_archive: false
        # apt_dev: false
        # apt_build: false
        # apt_libs: false
        # APT (2) -------------------------------
        # apt_vpn: false
        # apt_go: false
        # apt_php: false
        # apt_rasp_pi_pkg: false
        # apt_qemu_guest_agent: true
        # DPKG ----------------------------------
        # dpkg_...: false
        # SNAP ----------------------------------
        # snap_microk8s: false
        # snap_multipass: false
        snap_btop: true
        # OTHER --------------------------------
        git: true
        zsh: true
        # tmux: false
        # python: false # base|dev
        # go_kompose: false
        # ruby: false
        # npm: false
        # mongodb: false
        # java: false # base|dev
    ### -------------------------
    - role: ansible-netplan
      netplan_service_name: "{{ service_name }}"
      when: netplan_setup is defined and netplan_setup | bool
    ### -------------------------

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Docker installer
  ansible.builtin.import_playbook: playbook-s-docker.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Kubernetes installer
  ansible.builtin.import_playbook: playbook-s-kubernetes.yml
