---
# playbook server

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: CIS installer
  ansible.builtin.import_playbook: playbook-s-cis.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Pre installer
  ansible.builtin.import_playbook: playbook-s-pre-install.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Server installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - servers
  roles:
    ### -------------------------
    - role: ansible-install-server
      install_server_service_name: "{{ service_name }}"
      install_server_config:
        dev: true
        apt_base: true
        apt_dev: true
        apt_exfat: true
        apt_libs: true # base|dev
        apt_vpn: true
        apt_go: true
        # apt_rasp_pi_pkg: no
        # apt_qemu_guest_agent: no
        # dpkg_...: no
        # snap_...: no
        # snap_microk8s: no
        snap_btop: true
        git: true
        zsh: true
        tmux: true
        python: true # base|dev
        # go: no
        # go_kompose: no
        ruby: true
        npm: true
        # mongodb: no
        java: true # base|dev
    ### -------------------------
    - role: ansible-netplan
      netplan_service_name: "{{ service_name }}"
      when: netplan_setup is defined and netplan_setup | bool
    ### -------------------------

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Docker installer
  ansible.builtin.import_playbook: playbook-s-docker.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Kubernetes installer
  ansible.builtin.import_playbook: playbook-s-kubernetes.yml

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Hardening scan
  ansible.builtin.import_playbook: playbook-s-hardening.yml
