---
# playbook kubernetes

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: kubernetes installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - kubernetes
  roles:
    ### -------------------------
    - role: ansible-kubernetes
    ### -------------------------
