---
# playbook server

# ------------------------------------------------------------------------------
- name: HARDENING PLAYBOOKS
  ansible.builtin.import_playbook: playbook-sec-short.yml

# ------------------------------------------------------------------------------
- name: Server installer
  remote_user: "{{ ansible_user }}"
  hosts:
    - servers
  roles:
    ### -------------------------
    - role: ansible-install-server
      clients: "{{ pl_a_clients }}"
      install_server_service_name: "{{ pl_a_service_name }}"
      install_server_config:
        env_tun_setup: true
        # APT -------------------------------
        apt_base: true
        # apt_exa: false
        apt_eza: true
        apt_bat: true
        apt_auth_priv: true
        apt_cert: true
        apt_archive: true
        apt_dev: true
        apt_build: true
        apt_libs: true
        apt_java_jre_headless: true
        apt_snap: true
        apt_vpn_wireguard: true
        apt_qemu_guest_agent: true
        # SNAP ----------------------------------
        snap_btop: true
        snap_glow: true
        snap_nmap: true
        # OTHER --------------------------------
        inst_git_conf: true
        inst_fonts: true
        inst_zsh_conf: true
        inst_tmux_conf: true
        inst_nvim_conf: true
        # PYTHON --------------------------------
        apt_python: true
        apt_python_pip: true
        apt_python_venv: true
        apt_python_dev: true
        pip_s_tui: true
        pip_autopep8: true
        pip_black: true
        pip_mypy: true
        pip_pre_commit: true
        pip_ansible: true

# ------------------------------------------------------------------------------
- name: Container installer
  ansible.builtin.import_playbook: playbook-s-container.yml
