---
# playbook sec short

# ------------------------------------------------------------------------------
- name: CIS installer
  ansible.builtin.import_playbook: playbook-s-cis.yml

# ------------------------------------------------------------------------------
- name: Pre installer
  ansible.builtin.import_playbook: playbook-s-pre-install.yml

# ------------------------------------------------------------------------------
- name: Hardening scan
  ansible.builtin.import_playbook: playbook-s-hardening.yml
