---
# playbook hardening

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Setup Security Services and improves
  remote_user: "{{ ansible_user }}"
  hosts:
    - sec
  roles:
    ### -------------------------
    - role: ansible-security
      security_setup_services:
        auditd: "{{ pl_a_auditd_setup | default(true) }}"
        fail2ban: "{{ pl_a_fail2ban_setup | default(true) }}"
        snmp: "{{ pl_a_snmp_setup | default(false) }}"
    ### -------------------------
