---
# playbook sec short

# ------------------------------------------------------------------------------
- name: CIS installer
  ansible.builtin.import_playbook: playbook-s-cis.yml

# ------------------------------------------------------------------------------
- name: Pre installer
  ansible.builtin.import_playbook: playbook-s-pre-install.yml

# ------------------------------------------------------------------------------
- name: Hardening scan
  ansible.builtin.import_playbook: playbook-s-hardening.yml

# ------------------------------------------------------------------------------
- name: "RESTART PLAYBOOKS"
  remote_user: "{{ ansible_user }}"
  hosts: all
  tasks:
    - name: "RESTART | Restart the system"
      become: true
      ansible.builtin.command: /sbin/reboot
      async: 1
      poll: 0
      changed_when: false
      failed_when: false

    - name: "RESTART | Wait for the system to restart"
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300
