---
# playbook hardening

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
- name: Setup hardening scan
  remote_user: "{{ ansible_user }}"
  hosts:
    - sec
  become: true
  roles:
    ### -------------------------
    - role: ansible-lynis
      lynis_deploy_method: git
      lynis_git_repo: "https://github.com/CISOfy/lynis"
      lynis_report_from: "{{ hardening_lynis_report_from | default('root') }}"
      lynis_report_to: "{{ hardening_lynis_report_to | default('root') }}"
      lynis_cron_hour: 21
      lynis_cron_minute: 42
      lynis_cron_dow: 7
      when:
        - hardening_scan is defined
        - hardening_scan | bool
    ### -------------------------
    - role: ansible-security
      security_setup_services:
        - auditd: "{{ security_setup_services_auditd | default(true) }}"
        - fail2ban: "{{ security_setup_services_fail2ban | default(true) }}"
    ### -------------------------
