---
# playbook PRE

# ------------------------------------------------------------------------------
- name: PRE | configuration task (0) | include pre-task playbook
  import_playbook: ./pre-tasks.yml
  vars:
    ansible_user_conf_on_hosts:
      - pre
    ansible_user_conf_name: "{{ ansible_user }}"
    ansible_user_conf_update: "{{ pl_a_user_config.is_update | bool }}"
    ansible_user_conf_shell: "{{ pl_a_user_config.shell | default('/bin/bash') }}"
    ansible_user_conf_password: "{{ pl_a_user_config.password }}"
    ansible_user_conf_group: "{{ pl_a_user_config.group | default('adm,cdrom,sudo') }}"
    ansible_user_conf_system: "{{ pl_a_user_config.system | default('no') | bool }}"
    ansible_user_conf_append: "{{ pl_a_user_config.append | default('yes') | bool }}"
    ansible_user_conf_createhome: "{{ pl_a_user_config.createhome | default('yes') | bool }}"
    ansible_user_conf_home: "{{ pl_a_user_config.home | default('/home/' + ansible_user) }}"
    ansible_user_conf_add_ssh_key: "{{ pl_a_user_config.add_ssh_key | default('yes') | bool }}"
    ansible_user_conf_clients: "{{ pl_a_clients }}"
    ansible_host_conf_hostname: "{{ ansible_host_hostname | default(ansible_hostname) }}"
  when:
    - pl_a_user_setup is defined
    - pl_a_user_setup | bool

# ------------------------------------------------------------------------------
- name: PRE | configuration task (1) | updater
  remote_user: "{{ ansible_user }}"
  hosts:
    - pre
  vars:
    pl_a_updater_unattended_allowed_origins:
      # - "Docker:${distro_codename}"
      - "${distro_id}:${distro_codename}"
      - "${distro_id}:${distro_codename}-security"
      - "${distro_id}:${distro_codename}-updates"
      - "${distro_id}ESMApps:${distro_codename}-apps-security"
      - "${distro_id}ESM:${distro_codename}-infra-security"
    pl_a_updater_unattended_origins_patterns:
      # - "o=Docker,a=${distro_codename},l=Docker CE"
      # - "o=Ubuntu,a=${distro_codename},n=${distro_codename},l=Ubuntu"
      - "o=Ubuntu,a=${distro_codename}-security,n=${distro_codename},l=Ubuntu"
      - "o=Ubuntu,a=${distro_codename}-updates,n=${distro_codename},l=Ubuntu"
      # - "o=Ubuntu,a=${distro_codename}-proposed-updates,n=${distro_codename},l=Ubuntu"
      # - "o=Ubuntu,a=${distro_codename}-backports,n=${distro_codename},l=Ubuntu"
  roles:
    - role: ansible-updater
      clients: "{{ pl_a_clients }}"
      updater_config:
        set_timezone: true
        set_time_sync: true
        set_language: true
        update_upgrade: true
        setup_zfs: true
        setup_unattended: true
      updater_unattended_allowed_origins: "{{ pl_a_updater_unattended_allowed_origins + pl_a_updater_unattended_allowed_origins_ext | default([]) }}"
      updater_unattended_origins_patterns: "{{ pl_a_updater_unattended_origins_patterns + pl_a_updater_unattended_origins_patterns_ext | default([]) }}"

# ------------------------------------------------------------------------------
- name: PRE | configuration task (2) | ufw
  remote_user: "{{ ansible_user }}"
  hosts:
    - pre
  vars:
    pl_a_ufw_rules_default:
      - rule: allow
        to_port: 22
        protocol: tcp
        interface: "{{ ansible_default_ipv4['interface'] }}"
        comment: "allow incoming connection on standard ssh port"
  tasks:
    # --------------------------------------------------------------------------
    - name: "PRE | setup ufw | logging"
      become: true
      community.general.ufw:
        logging: "{{ pl_a_ufw_logging_level }}"
      when:
        - (pl_a_ufw_setup_enable is defined and pl_a_ufw_setup_enable | bool) or pl_a_ufw_logging_level is defined
    # --------------------------------------------------------------------------
    - name: "PRE | setup ufw | rules"
      become: true
      community.general.ufw:
        rule: "{{ item.rule }}"
        interface: "{{ item.interface | default('') }}"
        direction: "{{ item.direction | default('in') }}"
        from_ip: "{{ item.from_ip | default('any') }}"
        to_ip: "{{ item.to_ip | default('any') }}"
        from_port: "{{ item.from_port | default('') }}"
        to_port: "{{ item.to_port | default('') }}"
        protocol: "{{ item.protocol | default('any') }}"
        route: "{{ item.route | default(omit) }}"
        log: "{{ item.log | default(false) }}"
        comment: "{{ item.comment | default(omit) }}"
      with_items: "{{ pl_a_ufw_rules_default + pl_a_ufw_rules_extended | default([]) }}"
      when:
        - pl_a_ufw_setup_enable is defined
        - pl_a_ufw_setup_enable | bool

# ------------------------------------------------------------------------------
- name: PRE | configuration task (3) | ssh/netplan
  remote_user: "{{ ansible_user }}"
  hosts:
    - pre
  roles:
    ### -------------------------
    - role: ansible-ssh
      clients: "{{ pl_a_clients }}"
      when:
        - pl_a_ssh_setup_enable | bool
    ### -------------------------
    - role: ansible-netplan
      netplan_service_name: "{{ pl_a_service_name }}"
      when:
        - pl_a_netplan_setup is defined
        - pl_a_netplan_setup | bool

# ------------------------------------------------------------------------------
- name: PRE | configuration task (4) | include mailing playbook
  import_playbook: ./playbook-s-pre-mailing.yml
