---
name: Ansible Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout (with submodules)
        uses: actions/checkout@v7.0.1
        with:
          # roles are git submodules and are referenced by the playbooks
          submodules: recursive

      # https://github.com/ansible/galaxy/collections
      - name: Install collections
        run: ansible-galaxy collection install -r requirements.yml

      # https://github.com/ansible/ansible-lint
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v26.6.0
